### ISSUE TITLE
uC firmware update fails with hardsploit_gui 2.3.2

### ISSUE THREAD

**Issue by thelumberjhack** [OPALESECURITY/hardsploit-gui#6]
Hi,

I tried to update the uC firmware after updating hardsploit_gui from 2 different clean install (kali and ubuntu):

``` bash
yannick@ubuntu:~$ Hardsploit is connected
dfu-util 0.8

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2014 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to dfu-util@lists.gnumonks.org
```

The board is detected but on kali, dfu-util outputs an error message that mentions a missing HARDSPLOIT_FIRMWARE_UC.bin file.

FYI the hardsploit_gui is in v2.3.2, API v2.0 and HW is 1.00 SW: 1.0.2

**Comment by julienmoinard** [comment]
Hi,
Thank you for your feedback.
This issue is due to the new path of microcontroller firmware.

'/../Firmware/UC/HARDSPLOIT_FIRMWARE_UC.bin'")

instead of 
'/../Firmware**s**/UC/HARDSPLOIT_FIRMWARE_UC.bin'")

Sorry for that.
Fix in progress ASAP

Julien.

**Comment by thelumberjhack** [comment]
OK, no problem, will wait for the update :+1: 

Yannick

**Comment by julienmoinard** [comment]
hardsploit_gui (2.4.0) is available to fix this issue, sorry :)

`gem update hardsploit_gui`

Thank you Yannick for the feedback !
Julien.
